name: Build

on:
  push:
  workflow_dispatch:

env:
  NODE_VERSION: '14.x'

jobs:
  analyse-code-base:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      with:
        # Full git history is needed to get a proper list of changed files
        fetch-depth: 0

    - name: Setup Node.js ${{ env.NODE_VERSION }} Environment
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install Dependencies
      run: npm ci

    - name: Lint Code Base
      run: npm run lint

    # TODO: Add some tests and get this running
    # - name: Test Code Base
    #   run: npm run test

    - name: Super Lint Code Base
      uses: docker://ghcr.io/github/super-linter:slim-v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
